queue_rules:
  - name: default
    queue_conditions:
      - status-success=test-specific-version (macos-latest)
      - status-success=test-specific-version (windows-latest)
      - status-success=test-specific-version (ubuntu-latest)
      - status-success=test-latest (macos-latest)
      - status-success=test-latest (windows-latest)
      - status-success=test-latest (ubuntu-latest)
      - status-success=check-conventional-commits / check-conventional-commits
      - status-success=lint-markdown
      - base=main
      - author=dependabot[bot]
    merge_conditions:
      - status-success=test-specific-version (macos-latest)
      - status-success=test-specific-version (windows-latest)
      - status-success=test-specific-version (ubuntu-latest)
      - status-success=test-latest (macos-latest)
      - status-success=test-latest (windows-latest)
      - status-success=test-latest (ubuntu-latest)
      - status-success=check-conventional-commits / check-conventional-commits
      - status-success=lint-markdown
    merge_method: merge

pull_request_rules:
  - name: automatic rebase for dependencies
    conditions: []
    actions:
      queue:
