on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  test-latest:
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - run: specdown --help

  test-specific-version:
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          version: 0.55.5
      - run: specdown --help

  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: PurpleBooth/gfmfmt-action@v2.0.14
        with:
          pattern: ^(?!\./CHANGELOG).*\.md$

  check-conventional-commits:
    uses: armakuni/github-actions/.github/workflows/check-conventional-commits.yml@v0.14.4

  release:
    if: github.ref == 'refs/heads/main'
    needs:
      - test-specific-version
      - test-latest
      - check-conventional-commits
      - lint-markdown
    uses: armakuni/github-actions/.github/workflows/tag-and-release.yml@v0.14.4
    with:
      download-artifacts: true
      release-artifacts: ./bins/*
